---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: podinfo
  name: podinfo
spec:
  ports:
  - name: http
    port: 9898
    protocol: TCP
  selector:
    app: podinfo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: podinfo
  name: podinfo
spec:
  replicas: 1
  selector:
    matchLables:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:4.0.6
          env:
          - name: NODE_NAME
            valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 9898
          resources:
            limits:
              cpu: 100m
              memory: 40Mi
            requests:
              cpu: 20m
              memory: 40Mi
        - name: tunnel
          image: msnelling/cloudflared:2020.6.3
          env:
            - name: TUNNEL_HOSTNAME
              value: 
            - name: TUNNEL_ORIGIN_URL