on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo snap install microk8s --classic --channel=1.18/stable
    - uses: mxschmitt/action-tmate@v2
    - run: |
        sudo usermod -a -G microk8s $USER
        sudo chown -f -R $USER ~/.kube
