on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment variables
      run: |
        export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        echo "::set-env name=PR_NUMBER::$PR_NUMBER"
        echo "::set-env name=CLUSTER_HOST::pr-$PR_NUMBER-cluster-in-ci.taras.app"

    - name: Create Cloudflare Credentials file
      run: mkdir $HOME/.cloudflared && echo $CERT_PEM > $HOME/.cloudflared/cert.pem
      env:
        CERT_PEM: ${{secrets.CLOUDFLARED_TUNNEL_PEM}}

    - name: Install microk8s with snap
      run: sudo snap install microk8s --classic --channel=1.18/stable

    - name: Verify that microk8s started
      run: sudo microk8s status --wait-ready

    - name: "Enable microk8s extensions: dns, helm3"
      run: sudo microk8s enable dns helm3

    - name: Write Cloudflare Credentials to Kubernetes secrets
      run: sudo microk8s kubectl create secret generic $CLUSTER_HOST --from-file="$HOME/.cloudflared/cert.pem"
    - run: sudo microk8s kubectl get secret

    - name: Start podinfo
      run: sudo microk8s kubectl apply -k github.com/stefanprodan/podinfo//kustomize

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2