on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: sudo snap install microk8s --classic --channel=1.18/stable
    - run: sudo microk8s status --wait-ready
    - run: sudo microk8s enable dns helm

    - name: Create Cloudflare Credentials file
      run: mkdir $HOME/.cloudflared && echo $CLOUDFLARED_TUNNEL_PEM > $HOME/.cloudflared/cert.pem

    - name: Write Cloudflare Credentials to Kubernetes secrets
      run: sudo microk8s kubectl create secret generic taras.app --from-file="$HOME/.cloudflared/cert.pem"
    - run: sudo microk8s kubectl get secret

    - run: sudo microk8s helm --version
