on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Setup environment variables
      run: |
        export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = \"/\" } ; { print $3 }')
        echo "::set-env PR_NUMBER=$PR_NUMBER"
        echo "::set-env CLUSTER_CNAME=pr-$PR_NUMBER.cluster-in-ci"
        echo "::set-env CLUSTER_HOST=$CLUSTER_CNAME.taras.app"

    - name: Install Cloudflare CLI
      run: npm install -g cloudflare-cli

    - run: echo $CLUSTER_CNAME

    - name: Create subdomain for PR
      run: cfcli -a -t CNAME add $CLUSTER_CNAME cluster-in-ci.taras.app
      env:
        CF_API_KEY: ${{secrets.CLOUDFLARE_DNS_API_TOKEN}}
        CF_API_DOMAIN: taras.app

    - name: Create Cloudflare Credentials file
      run: mkdir $HOME/.cloudflared && echo ${{secrets.CLOUDFLARED_TUNNEL_PEM}} > $HOME/.cloudflared/cert.pem

    # - name: Install microk8s with snap
    #   run: sudo snap install microk8s --classic --channel=1.18/stable

    # - name: Verify that microk8s started
    #   run: sudo microk8s status --wait-ready

    # - name: "Enable microk8s extensions: dns, helm3"
    #   run: sudo microk8s enable dns helm3

    # - name: Write Cloudflare Credentials to Kubernetes secrets
    #   run: sudo microk8s kubectl create secret generic taras.app --from-file="$HOME/.cloudflared/cert.pem"
    # - run: sudo microk8s kubectl get secret

    # - run: sudo microk8s helm3 repo add podinfo https://stefanprodan.github.io/podinfo
    # - run: |
    #     sudo microk8s helm3 upgrade --install --wait frontend \
    #     --set replicaCount=1 \
    #     --set backend=http://backend-podinfo:9898/echo \
    #     podinfo/podinfo
    
    # - name: "Test podinfo has hook-delete-policy: hook-succeeded"
    #   run: sudo microk8s helm3 test frontend
