on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo snap install microk8s --classic --channel=1.18/stable
    - run: sudo microk8s status --wait-ready
    - run: sudo microk8s enable dns ingress
    - name: Install Infopod
      run: sudo microk8s kubectl apply -k github.com/stefanprodan/podinfo//kustomize
    - run: sudo microk8s kubectl expose deployment podinfo --type=LoadBalancer --name=podinfo-http
    - run: sudo microk8s kubectl get services podinfo-http
    - uses: mxschmitt/action-tmate@v2
