on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Test CloudFlare CLI"
      uses: dpig/cloudflare-cli:latest
      run: cfcli ls
      env:
        CF_API_KEY: $CLOUDFLARE_DNS_API_TOKEN
        CF_API_DOMAIN: taras.dev


    # - name: Install microk8s with snap
    #   run: sudo snap install microk8s --classic --channel=1.18/stable

    # - name: Verify that microk8s started
    #   run: sudo microk8s status --wait-ready

    # - name: "Enable microk8s extensions: dns, helm3"
    #   run: sudo microk8s enable dns helm3

    # - name: Create Cloudflare Credentials file
    #   run: mkdir $HOME/.cloudflared && echo $CLOUDFLARED_TUNNEL_PEM > $HOME/.cloudflared/cert.pem

    # - name: Write Cloudflare Credentials to Kubernetes secrets
    #   run: sudo microk8s kubectl create secret generic taras.app --from-file="$HOME/.cloudflared/cert.pem"
    # - run: sudo microk8s kubectl get secret

    # - run: sudo microk8s helm3 repo add podinfo https://stefanprodan.github.io/podinfo
    # - run: |
    #     sudo microk8s helm3 upgrade --install --wait frontend \
    #     --set replicaCount=1 \
    #     --set backend=http://backend-podinfo:9898/echo \
    #     podinfo/podinfo
    
    # - name: "Test podinfo has hook-delete-policy: hook-succeeded"
    #   run: sudo microk8s helm3 test frontend
