on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup aliases
      run: |
        cat <<EOT >> $HOME/.bash_profile
          alias kubectl="sudo microk8s kubectl"
          alias microk8s="sudo microk8s"
          alias helm="sudo microk8s helm"
        EOT
        source $HOME/.bash_profile

    - run: sudo snap install microk8s --classic --channel=1.18/stable
    - run: microk8s status --wait-ready
      
    - run: microk8s enable dns helm

    - name: Create Cloudflare Credentials file
      run: mkdir $HOME/.cloudflared && echo $CLOUDFLARED_TUNNEL_PEM > $HOME/.cloudflared/cert.pem

    - name: Write Cloudflare Credentials to Kubernetes secrets
      run: kubectl create secret generic taras.app --from-file="$HOME/.cloudflared/cert.pem"
    - run: kubectl get secret

    - run: helm --version